services:

  backlogdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5434"
    volumes:
      - backlog_db:/var/lib/postgresql/data
  web:
    build: .
    container_name: web-backlog
    command: >
      /bin/sh -c "alembic upgrade head
      && uvicorn entrypoints.fastapi.main:app --host 0.0.0.0 --port 8000 --reload --forwarded-allow-ips=*"
    ports:
      - "8000:8000"
    depends_on:
      - backlogdb
    env_file:
      - .env
    volumes:
      - .:/backlogforgames

volumes:
  backlog_db:
    external: True