"""add users table

Revision ID: 00c2a2f493e1
Revises:
Create Date: 2025-11-03 10:15:26.774310+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '00c2a2f493e1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uuid', sa.UUID(), nullable=False, comment='User ID'),
        sa.Column('nickname', sa.Text(), nullable=False, comment='User nickname'),
        sa.Column('email', sa.Text(), nullable=False, comment='User email'),
        sa.Column('password', sa.Text(), nullable=False),
        sa.Column('date_birth', sa.Date(), nullable=True, comment='Date of birth user'),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
            comment='Date of registration user',
        ),
        sa.Column('about', sa.Text(), nullable=True, comment='Information about yourself'),
        sa.PrimaryKeyConstraint('id'),
        schema='backlog_app',
    )
    op.create_index(op.f('ix_backlog_app_users_uuid'), 'users', ['uuid'], unique=True, schema='backlog_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backlog_app_users_uuid'), table_name='users', schema='backlog_app')
    op.drop_table('users', schema='backlog_app')
    # ### end Alembic commands ###
