"""add unique indexes on users email and nickname

Revision ID: 64e543785350
Revises: 00c2a2f493e1
Create Date: 2026-09-26 12:18:42.953674+00:00

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '64e543785350'
down_revision: str | Sequence[str] | None = '00c2a2f493e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_backlog_app_users_email'), 'users', ['email'], unique=True, schema='backlog_app')
    op.create_index(op.f('ix_backlog_app_users_nickname'), 'users', ['nickname'], unique=True, schema='backlog_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backlog_app_users_nickname'), table_name='users', schema='backlog_app')
    op.drop_index(op.f('ix_backlog_app_users_email'), table_name='users', schema='backlog_app')
    # ### end Alembic commands ###
