"""add user profile flags

Revision ID: bbdaef3f7431
Revises: 64e543785350
Create Date: 2026-09-27 09:27:32.412385+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'bbdaef3f7431'
down_revision: str | Sequence[str] | None = '64e543785350'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('avatar_url', sa.Text(), nullable=True, comment='User avatar URL'),
        schema='backlog_app',
    )
    op.add_column(
        'users',
        sa.Column(
            'email_confirmed',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False,
            comment='Email confirmation flag',
        ),
        schema='backlog_app',
    )
    op.add_column(
        'users',
        sa.Column(
            'is_admin',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False,
            comment='Administrator flag',
        ),
        schema='backlog_app',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin', schema='backlog_app')
    op.drop_column('users', 'email_confirmed', schema='backlog_app')
    op.drop_column('users', 'avatar_url', schema='backlog_app')
    # ### end Alembic commands ###
